---
# Install packages on a debian family distribution.

- name: Install openjdk repo
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Install openjdk package
  apt: name={{ item }} state=latest update_cache=yes install_recommends=no
  with_items:
    - openjdk-8-jdk
    - cloud-init
    - emacs24-nox

- name: Add Elasticsearch apt key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present

- name: Install Elasticsearch repo
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present

- name: Install Elasticsearch package
  apt: name={{ item }} update_cache=yes state=latest install_recommends=no
  with_items:
    - elasticsearch

- name: Configure Elasticsearch.
  include: elasticsearch.yml
